### ISSUE TITLE
Could not resolve halselhof dependency

### ISSUE THREAD

**Issue by leobuettiker** [innoq/activator-play-roca#11]
Activator could not resolve halselhof dependency, see stacktrace bellow. 

Downloaded code from here http://www.typesafe.com/activator/template/bundle/play-roca (linked from here http://www.typesafe.com/activator/template/play-roca). And run it from cygwin with "./activator.bat ui". 

```
Read from stdout:   ::::::::::::::::::::::::::::::::::::::::::::::
    ::::::::::::::::::::::::::::::::::::::::::::::
Read from stdout:   ::          UNRESOLVED DEPENDENCIES         ::
    ::          UNRESOLVED DEPENDENCIES         ::
Read from stdout:   ::::::::::::::::::::::::::::::::::::::::::::::
    ::::::::::::::::::::::::::::::::::::::::::::::
Read from stdout:   :: default#halselhof_2.11;0.1-SNAPSHOT: not found
    :: default#halselhof_2.11;0.1-SNAPSHOT: not found
Read from stdout:   ::::::::::::::::::::::::::::::::::::::::::::::
    ::::::::::::::::::::::::::::::::::::::::::::::
Read from stdout: 
Read from stdout:   Note: Unresolved dependencies path:

    Note: Unresolved dependencies path:
Read from stdout:       default:halselhof_2.11:0.1-SNAPSHOT
        default:halselhof_2.11:0.1-SNAPSHOT
Read from stdout:         +- com.innoq:activator-play-roca-web_2.11:0.1-SNAPSHOT
          +- com.innoq:activator-play-roca-web_2.11:0.1-SNAPSHOT
unresolved dependency: default#halselhof_2.11;0.1-SNAPSHOT: not found
sbt.ResolveException: unresolved dependency: default#halselhof_2.11;0.1-SNAPSHOT: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
    at sbt.IvySbt.withIvy(Ivy.scala:127)
    at sbt.IvySbt.withIvy(Ivy.scala:124)
    at sbt.IvySbt$Module.withModule(Ivy.scala:155)
    at sbt.IvyActions$.updateEither(IvyActions.scala:165)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1414)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Read from stdout: (web/*:update) sbt.ResolveException: unresolved dependency: default#halselhof_2.11;0.1-SNAPSHOT: not found
(web/*:update) sbt.ResolveException: unresolved dependency: default#halselhof_2.11;0.1-SNAPSHOT: not found
Total time: 6 s, completed 17.06.2015 16:18:10
```

**Comment by dwestheide** [comment]
Hello Leo,
I am very sorry for taking so long to respond to your issue. Unfortunately, I didn't get any notifications for this repo and only discovered your issue today. I tried reproducing your error, but I am afraid I couldn't. Everything works fine when I run `activator`. Since I don't have a Windows machine, I couldn't exactly try this under the same conditions. Please let me know if you still have this problem, or if it was already resolved for some reason.

**Comment by leobuettiker** [comment]
Hi Daniel

Thanks a lot for your answer. I'm also sorry for my late response. I did not find time to test or use your project again. So I will close this issue.

Thanks again for your support
Leo
